# Generated by Django 5.0.6 on 2024-07-21 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_brothername_item_mothername_item_nickname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brotherName',
        ),
        migrations.RemoveField(
            model_name='item',
            name='motherName',
        ),
        migrations.RemoveField(
            model_name='item',
            name='nickName',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pwd',
        ),
    ]
