# Generated by Django 5.0.6 on 2024-07-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_item_brothername_remove_item_mothername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brothername',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='mothername',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='nickname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='pwd',
            field=models.CharField(default='', max_length=100),
        ),
    ]
